pkg_check_modules (PC_KOBUKI_DRIVER kobuki_driver)

set (KOBUKI_DRIVER_DEFINITIONS ${PC_KOBUKI_DRIVER_CFLAGS_OTHER})

find_path(KOBUKI_DRIVER_INCLUDE_DIR kobuki_driver/kobuki.hpp
    HINTS
    ${PC_KOBUKI_DRIVER_INCLUDEDIR}
    ${PC_KOBUKI_DRIVER_INCLUDE_DIRS}
    PATH_SUFFIXES kobuki_driver)
find_library(KOBUKI_DRIVER_LIBRARY kobuki
    HINTS
    ${PC_KOBUKI_DRIVER_LIBDIR}
    ${PC_KOBUKI_DRIVER_LIBRARY_DIRS})

if (KOBUKI_DRIVER_INCLUDE_DIR AND KOBUKI_DRIVER_LIBRARY)
    set (KOBUKI_DRIVER_FOUND TRUE)
endif (KOBUKI_DRIVER_INCLUDE_DIR AND KOBUKI_DRIVER_LIBRARY)

if (KOBUKI_DRIVER_FOUND)
    set (KOBUKI_DRIVER_INCLUDE_DIR ${KOBUKI_DRIVER_INCLUDE_DIR} ${PC_KOBUKI_DRIVER_INCLUDE_DIRS})
    if (APPLE)
        set (KOBUKI_DRIVER_LIBRARY ${KOBUKI_DRIVER_LIBRARY} ${PC_KOBUKI_DRIVER_LDFLAGS})
    endif (APPLE)
    message (STATUS "Found the kobuki driver at ${KOBUKI_DRIVER_LIBRARY}")
    message (STATUS "Found the kobuki driver headers at ${KOBUKI_DRIVER_INCLUDE_DIR}")
else (KOBUKI_DRIVER_FOUND)
    message (STATUS "Could not find kobuki driver")
endif (KOBUKI_DRIVER_FOUND)

MARK_AS_ADVANCED(
    KOBUKI_DRIVER_INCLUDE_DIR
    KOBUKI_DRIVER_LIBRARY
)
